apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce-blue
  labels:
    app: ecommerce
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "ecommerce"
  DB_USER: "postgres"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  LOG_LEVEL: "info"
