name: Deploy Desktop Services

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'desktop/**'

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Notice
        run: echo "Use Terraform Operations workflow for Cassandra deployment"
